import { $ } from "bun";

try {
  await $`capnp-es node_modules/workerd/workerd.capnp -ots`;
} catch (error) {
  console.error(error);
  console.error(
    "This is likely because you don't have capnp installed on your machine. See https://capnproto.org/install.html for instructions.",
  );
  process.exit(1);
}

const source = Bun.file("node_modules/workerd/workerd.ts");
const target = Bun.file("src/core/workerd/internal/config.capnp.ts");

await target.write(`// Generated by src/core/scripts/generate-capnp.ts. Do not edit this file manually.
${(await source.text()).split("\n").slice(1).join("\n")}`);
await $`oxfmt src/core/workerd/internal/config.capnp.ts`;
