// This file is generated by the effect-acp package. Do not edit manually.
// Current ACP schema release: schema-v2.0.0-alpha.3

export const AGENT_METHODS = {
  initialize: "initialize",
  auth_login: "auth/login",
  providers_list: "providers/list",
  providers_set: "providers/set",
  providers_disable: "providers/disable",
  session_new: "session/new",
  session_set_config_option: "session/set_config_option",
  session_prompt: "session/prompt",
  session_cancel: "session/cancel",
  mcp_message: "mcp/message",
  session_list: "session/list",
  session_delete: "session/delete",
  session_fork: "session/fork",
  session_resume: "session/resume",
  session_close: "session/close",
  auth_logout: "auth/logout",
  nes_start: "nes/start",
  nes_suggest: "nes/suggest",
  nes_accept: "nes/accept",
  nes_reject: "nes/reject",
  nes_close: "nes/close",
  document_did_open: "document/didOpen",
  document_did_change: "document/didChange",
  document_did_close: "document/didClose",
  document_did_save: "document/didSave",
  document_did_focus: "document/didFocus",
} as const;

export const CLIENT_METHODS = {
  session_request_permission: "session/request_permission",
  session_update: "session/update",
  mcp_connect: "mcp/connect",
  mcp_message: "mcp/message",
  mcp_disconnect: "mcp/disconnect",
  elicitation_create: "elicitation/create",
  elicitation_complete: "elicitation/complete",
} as const;

export const PROTOCOL_VERSION = 2 as const;
