<script>
  import { page } from "$app/state";
</script>

<!-- Marker for kit's OWN rendered error page. Requests that reach the
     worker and 404 at kit's router render this component (through
     app.html); the assets-layer `404.html` fallback never does — the
     fallback is generated by a shell render (no route, no error). The
     404-page tests use its absence to prove a response came from the
     assets fallback, and its presence to prove the worker rendered it. -->
<h1 id="error-title">sveltekit-404-kit-error-page</h1>
<p id="error-status">status:{page.status}</p>
