import { defineConfig } from "tsdown";

export default defineConfig([
  {
    cwd: ".",
    entry: {
      "core/index": "src/core/index.ts",
      "astro/neon": "src/astro/neon.ts",
      "nextjs/neon": "src/nextjs/neon.ts",
      "nuxt/neon": "src/nuxt/neon.ts",
      "octane/neon": "src/octane/neon.ts",
      "react-router/neon": "src/react-router/neon.ts",
      "solidstart/neon": "src/solidstart/neon.ts",
      "tanstack-start/neon": "src/tanstack-start/neon.ts",
      "sveltekit/neon": "src/sveltekit/neon.ts",
      "vite/neon": "src/vite/neon.ts",
      "waku/neon": "src/waku/neon.ts",
      "vocs/neon": "src/vocs/neon.ts",
      // Standalone child-process entries (spawned by BuildChild.ts /
      // DevChild.ts, never imported) — must keep their own stable files at
      // dist/core/.
      "core/BuildChildRunner": "src/core/BuildChildRunner.ts",
      "core/DevChildRunner": "src/core/DevChildRunner.ts",
      "astro/index": "src/astro/index.ts",
      "astro/aws": "src/astro/aws.ts",
      "astro/node": "src/astro/node.ts",
      "astro/cloudflare": "src/astro/cloudflare.ts",
      "astro/entrypoints/aws-server": "src/astro/entrypoints/aws-server.ts",
      "astro/entrypoints/node-server": "src/astro/entrypoints/node-server.ts",
      "astro/source": "src/astro/source.ts",
      "astro/runtime/entrypoints/server":
        "src/astro/runtime/entrypoints/server.ts",
      "astro/runtime/entrypoints/image-passthrough-endpoint":
        "src/astro/runtime/entrypoints/image-passthrough-endpoint.ts",
      "nextjs/index": "src/nextjs/index.ts",
      "nextjs/aws": "src/nextjs/aws.ts",
      "nextjs/node": "src/nextjs/node.ts",
      "nextjs/source": "src/nextjs/source.ts",
      "aws-lambda/index": "src/aws-lambda/index.ts",
      "nuxt/index": "src/nuxt/index.ts",
      "nuxt/aws": "src/nuxt/aws.ts",
      "nuxt/node": "src/nuxt/node.ts",
      "nuxt/cloudflare": "src/nuxt/cloudflare.ts",
      "nuxt/source": "src/nuxt/source.ts",
      "octane/index": "src/octane/index.ts",
      "octane/aws": "src/octane/aws.ts",
      "octane/aws-adapter": "src/octane/aws-adapter.ts",
      "octane/node": "src/octane/node.ts",
      "octane/node-adapter": "src/octane/node-adapter.ts",
      "octane/cloudflare": "src/octane/cloudflare.ts",
      "octane/source": "src/octane/source.ts",
      "react-router/index": "src/react-router/index.ts",
      "react-router/aws": "src/react-router/aws.ts",
      "react-router/node": "src/react-router/node.ts",
      "solidstart/index": "src/solidstart/index.ts",
      "solidstart/aws": "src/solidstart/aws.ts",
      "solidstart/node": "src/solidstart/node.ts",
      "tanstack-start/index": "src/tanstack-start/index.ts",
      "tanstack-start/aws": "src/tanstack-start/aws.ts",
      "tanstack-start/node": "src/tanstack-start/node.ts",
      "sveltekit/index": "src/sveltekit/index.ts",
      "vinext/index": "src/vinext/index.ts",
      "vinext/aws": "src/vinext/aws.ts",
      "vinext/node": "src/vinext/node.ts",
      "vinext/cloudflare": "src/vinext/cloudflare.ts",
      "vinext/source": "src/vinext/source.ts",
      "vinext/cache/index": "src/vinext/cache/index.ts",
      "vinext/cache/kv": "src/vinext/cache/kv.ts",
      "vinext/cache/kv-runtime": "src/vinext/cache/kv-runtime.ts",
      "vinext/cache/redis": "src/vinext/cache/redis.ts",
      "vinext/cache/redis-runtime": "src/vinext/cache/redis-runtime.ts",
      "vinext/cache/s3": "src/vinext/cache/s3.ts",
      "vinext/cache/s3-runtime": "src/vinext/cache/s3-runtime.ts",
      "vite/index": "src/vite/index.ts",
      "vite/aws": "src/vite/aws.ts",
      "vite/node": "src/vite/node.ts",
      "sveltekit/aws": "src/sveltekit/aws.ts",
      "sveltekit/node": "src/sveltekit/node.ts",
      "sveltekit/cloudflare": "src/sveltekit/cloudflare.ts",
      "sveltekit/source": "src/sveltekit/source.ts",
      "waku/index": "src/waku/index.ts",
      "waku/adapter": "src/waku/adapter.ts",
      "waku/aws": "src/waku/aws.ts",
      "waku/node": "src/waku/node.ts",
      "waku/aws-adapter": "src/waku/aws-adapter.ts",
      "waku/cloudflare": "src/waku/cloudflare.ts",
      "waku/source": "src/waku/source.ts",
      "vocs/index": "src/vocs/index.ts",
      "vocs/cloudflare": "src/vocs/cloudflare.ts",
      "vocs/node": "src/vocs/node.ts",
      "vocs/source": "src/vocs/source.ts",
    },
    exports: false,
    outDir: "dist",
    tsconfig: "tsconfig.node.json",
    format: "esm",
    target: "esnext",
    dts: false,
    shims: false,
    sourcemap: true,
    deps: {
      alwaysBundle: [
        /^@astrojs\/internal-helpers(?:\/|$)/,
        /^@astrojs\/underscore-redirects(?:\/|$)/,
      ],
      // Fail the build if another dependency is bundled accidentally.
      onlyBundle: [
        "@astrojs/internal-helpers",
        "@astrojs/underscore-redirects",
      ],
    },
    inputOptions: {
      external: [
        /^(?:astro|cloudflare|virtual):/,
        /^nitropack(?:\/|$)/,
        /^alchemy(?:\/|$)/,
        /^@distilled\.cloud\/aws(?:\/|$)/,
      ],
      makeAbsoluteExternalsRelative: true,
    },
    outputOptions: {
      entryFileNames: "[name].js",
      chunkFileNames: "_chunks/[name]-[hash].js",
    },
  },
  {
    cwd: ".",
    entry: { "nuxt/dev/plugin": "src/nuxt/dev/plugin.ts" },
    exports: false,
    outDir: "dist",
    clean: false,
    tsconfig: "tsconfig.node.json",
    format: "esm",
    target: "esnext",
    dts: false,
    shims: false,
    sourcemap: true,
    deps: { onlyBundle: false },
    inputOptions: {
      external: [/^nitropack(?:\/|$)/],
      makeAbsoluteExternalsRelative: true,
    },
    outputOptions: {
      entryFileNames: "[name].js",
      codeSplitting: false,
    },
  },
]);
